FROM babelouest/tgz

ARG LIBCBOR_VERSION

# Install required packages
RUN apk add --no-cache \
		autoconf \
		automake \
		libcurl \
		curl-dev \
		libconfig-dev \
		jansson-dev \
		libgcrypt-dev \
		libmicrohttpd-dev \
		sqlite-dev \
		mariadb-dev \
		postgresql-dev \
		libtool \
		make \
		gcc \
		g++ \
		util-linux-dev \
		openldap-dev \
		wget \
		cmake \
		bash \
		zlib-dev \
    gnutls-utils \
    sqlite \
    check-dev \
		oath-toolkit-dev \
    libcbor-dev
